name: ai_background_remover
publish_to: 'none'
version: 0.2.0+2

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.2.0
  http: ^1.5.0
  path_provider: ^2.1.5
  share_plus: ^11.0.0
  google_mobile_ads: ^6.0.0
  in_app_purchase: ^3.2.1

flutter:
  uses-material-design: true
